Output spinner.gif
Set Width 1000
Set Height 300
Set FontSize 16
Set Shell bash
Set TypingSpeed 40ms

Type "export DEVSPACE_HOME=/var/folders/cn/2ck5t0pd23gc7324cjxtc76m0000gn/T/tmp.TpeDXIr8WW/home"
Enter
Type "clear"
Enter
Sleep 300ms
Type "./devspace project hydrate lazy"
Enter
Screenshot s1.png
Sleep 50ms
Screenshot s2.png
Sleep 50ms
Screenshot s3.png
Sleep 50ms
Screenshot s4.png
Sleep 1s
Screenshot s5.png
